repository:
  name: incubyte-assignment
  description: Magento E-commerce Test Automation with Cypress, BDD, and POM
  homepage: https://github.com/Yks-SE/incubyte-assignment
  topics: cypress, bdd, test-automation, magento, e-commerce
  private: false
  has_issues: true
  has_wiki: true
  has_downloads: true
  default_branch: master

branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Cypress Tests"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions: null

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: test
    color: 0052cc
    description: Adding or updating tests
  - name: ci
    color: 33b3ae
    description: Changes to CI configuration
  - name: security
    color: 1d76db
    description: Security related changes

# Issue templates
issue_template: |
  ## Description
  [Provide a detailed description of the issue]

  ## Steps to Reproduce
  1. [First Step]
  2. [Second Step]
  3. [And so on...]

  ## Expected Behavior
  [What you expected to happen]

  ## Actual Behavior
  [What actually happened]

  ## Environment
  - OS: [e.g., Windows 10]
  - Node Version: [e.g., 18.0.0]
  - Cypress Version: [e.g., 12.17.4]

  ## Additional Context
  [Add any other context about the problem here]

# Pull request template
pull_request_template: |
  ## Description
  [Provide a detailed description of the changes]

  ## Type of Change
  - [ ] Bug fix
  - [ ] New feature
  - [ ] Documentation update
  - [ ] Test update
  - [ ] CI/CD update

  ## Checklist
  - [ ] My code follows the style guidelines
  - [ ] I have performed a self-review
  - [ ] I have added tests that prove my fix is effective
  - [ ] New and existing tests pass locally
  - [ ] I have updated the documentation
  - [ ] My changes generate no new warnings 